version: '3.8'

services:
  tws-app:
    image: ${DOCKER_IMAGE:-iemafzal/tws-community-app}:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/welcome"]
      interval: 30s
      timeout: 10s
      retries: 3